# Generated by Django 3.0.8 on 2020-09-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='img',
            field=models.ImageField(upload_to='', verbose_name='Image'),
        ),
    ]
