# Generated by Django 3.0.8 on 2020-08-24 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='portfolio_page',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='portfolio_picture',
            field=models.ImageField(upload_to='media'),
        ),
    ]
