# Generated by Django 3.0.8 on 2020-09-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200824_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='portfolio_picture',
            field=models.ImageField(upload_to=''),
        ),
    ]
